'use client'

import Link from "next/link"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"

export default function PrivacyPage() {
  return (
    <main className="bg-midnight min-h-screen">
      <Navigation />
      <div className="px-[6%] py-20 max-w-4xl mx-auto">
        <h1 className="text-white font-serif text-4xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-muted-text text-sm mb-8">Last updated: June 15, 2026</p>

        <div className="prose prose-invert max-w-none text-cream space-y-6">
          <section>
            <p className="text-base leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold text-white mt-6 mb-3">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl font-semibold text-white mt-6 mb-3">Definitions</h3>
            <p className="text-sm mb-3">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2 text-sm">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BW Solutions, Hong Kong.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to HobbyAccelerator, accessible from hobbyaccelerator.com</li>
              <li><strong>You</strong> means the data subject and individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-xl font-semibold text-white mt-6 mb-3">Types of Data Collected</h3>
            
            <div className="ml-4">
              <h4 className="font-semibold text-white mt-4 mb-2">PERSONAL DATA</h4>
              <p className="text-sm mb-3">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-1 text-sm">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="font-semibold text-white mt-6 mb-2">USAGE DATA</h4>
              <p className="text-sm mb-3">
                Usage Data is collected automatically when using the Service.
              </p>
              <p className="text-sm mb-3">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="text-sm mb-3">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
              <p className="text-sm">
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
              </p>

              <h4 className="font-semibold text-white mt-6 mb-2">INFORMATION FROM THIRD-PARTY SOCIAL MEDIA SERVICES</h4>
              <p className="text-sm mb-3">
                The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
              </p>
              <ul className="list-disc pl-6 space-y-1 text-sm mb-3">
                <li>Google</li>
                <li>Meta</li>
                <li>TikTok</li>
                <li>YouTube</li>
                <li>Twitter</li>
              </ul>
              <p className="text-sm mb-3">
                If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
              </p>
              <p className="text-sm">
                You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Tracking Technologies and Cookies</h2>
            <p className="text-sm mb-3">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
            </p>
            <ul className="list-disc pl-6 space-y-3 text-sm">
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
              <li><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
            </ul>
            
            <p className="text-sm mt-4 mb-3">
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
            </p>

            <p className="text-sm mb-3 font-semibold text-white">We use both Session and Persistent Cookies for the purposes set out below:</p>
            
            <div className="ml-4 space-y-4">
              <div className="text-sm">
                <p className="font-semibold text-white mb-1">Necessary / Essential Cookies</p>
                <p className="mb-1"><strong>Type:</strong> Session Cookies</p>
                <p className="mb-1"><strong>Administered by:</strong> Us</p>
                <p><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
              </div>

              <div className="text-sm">
                <p className="font-semibold text-white mb-1">Cookies Policy / Notice Acceptance Cookies</p>
                <p className="mb-1"><strong>Type:</strong> Persistent Cookies</p>
                <p className="mb-1"><strong>Administered by:</strong> Us</p>
                <p><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</p>
              </div>

              <div className="text-sm">
                <p className="font-semibold text-white mb-1">Functionality Cookies</p>
                <p className="mb-1"><strong>Type:</strong> Session Cookies</p>
                <p className="mb-1"><strong>Administered by:</strong> Us</p>
                <p><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Use of Your Personal Data</h2>
            <p className="text-sm mb-3">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2 text-sm">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
              <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
              <li>To manage Your requests: To attend and manage Your requests to Us.</li>
              <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
              <li>Demand by Authorities: To meet any obligations of the Company to comply with any demand or request from public authorities.</li>
              <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
            </ul>

            <p className="text-sm mt-4 mb-3">We may share Your personal information in the following situations:</p>
            <ul className="list-disc pl-6 space-y-2 text-sm">
              <li><strong>With Service Providers:</strong> We may share Your personal information with any agents, contractors, sub-contractors, service providers to monitor and analyze the use of our Service, and to contact You.</li>
              <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
              <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
              <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
              <li><strong>With other users:</strong> When You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
              <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Use Of Data In Direct Marketing</h2>
            <p className="text-sm mb-3">
              Where you have given consent for Us to do so, we may use your data to provide you with direct marketing. In this connection, please note that:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-sm">
              <li>We may use the following categories of data for direct marketing purposes: name, email address, and usage information relating to your use of the Websites from time to time.</li>
              <li>The following classes of services, products and subjects may be marketed: news, special offers, promotions and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about.</li>
              <li>The above services, products and subjects may be provided or solicited by the Company and/or Our affiliates, business partners, and third party reward, co-branding or privileges programme providers or merchants.</li>
            </ul>
            <p className="text-sm mt-3">
              If You do not wish the Company to use or provide your data to other parties for use in direct marketing as described above, you may exercise your opt-out right by notifying Us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Retention of Your Personal Data</h2>
            <p className="text-sm mb-3">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-sm">
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Transfer of Your Personal Data</h2>
            <p className="text-sm mb-3">
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to, and maintained on, computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </p>
            <p className="text-sm mb-3">
              Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            </p>
            <p className="text-sm">
              The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Disclosure of Your Personal Data</h2>
            
            <h3 className="text-xl font-semibold text-white mt-6 mb-3">Business Transactions</h3>
            <p className="text-sm">
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            </p>

            <h3 className="text-xl font-semibold text-white mt-6 mb-3">Law Enforcement</h3>
            <p className="text-sm">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
            </p>

            <h3 className="text-xl font-semibold text-white mt-6 mb-3">Other Legal Requirements</h3>
            <p className="text-sm mb-3">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc pl-6 space-y-1 text-sm">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Security of Your Personal Data</h2>
            <p className="text-sm">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Links to Other Websites</h2>
            <p className="text-sm mb-3">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p className="text-sm">
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Changes to this Privacy Policy</h2>
            <p className="text-sm mb-3">
              In addition to our duty of confidentiality to Users, we shall at all times observe the above privacy policies and the Personal Data (Privacy) Ordinance ("the Ordinance") of the Hong Kong SAR in collecting, maintaining and using the personal data of the Users. We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-sm mb-3">
              We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
            </p>
            <p className="text-sm">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mt-8 mb-4">Contact Us</h2>
            <p className="text-sm mb-4">
              If you have any questions about this Privacy Policy or request for access to personal data or correction of personal data, You can contact us:
            </p>
            <ul className="list-none space-y-2 text-sm">
              <li><strong>By emailing:</strong> hello@hobbyaccelerator.com</li>
            </ul>
          </section>

          <section className="mt-12 pt-8 border-t border-border-white">
            <p className="text-sm text-muted-text">
              By using the HobbyAccelerator website, you consent to our Privacy Policy.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  )
}
